version: "3"

x-auth-env: &auth-env
  POSTGRES_USER: app
  POSTGRES_PASSWORD: 123qwe
  POSTGRES_DB: auth_database
  POSTGRES_HOST: postgres-authdb
  POSTGRES_PORT: 5432
  POSTGRES_ECHO: "True"
  REDIS_HOST: redis
  OAUTH_CLIENT_ID: 123123
  OAUTH_CLIENT_SECRET: 123123
  OAUTH_REDIRECT_URI: http://auth-api:8080/api/v1/auth/login/oauth/yandex/callback
  OAUTH_AUTH_SERVER: http://oauth2-server
  OAUTH_RESOURCE_SERVER: http://resource-server
  APP_ENABLE_TRACER: "False"

x-auth-migrations-env: &auth-migrations-env
  <<: *auth-env
  RUN_CMD: migrations

x-notification-env: &notification-env
  POSTGRES_USER: app
  POSTGRES_PASSWORD: 123qwe
  POSTGRES_DB: notifications
  POSTGRES_DBNAME: notifications
  POSTGRES_HOST: postgres-notifications
  POSTGRES_PORT: 5432
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_USERNAME: user
  RABBITMQ_PASSWORD: password

x-rabbitmq-env: &rabbitmq-env
  RABBITMQ_DEFAULT_USER: user
  RABBITMQ_DEFAULT_PASS: password

services:
  nginx:
    build: ugc_operations_service/nginx_tests
    restart: always
    networks:
      default:
        aliases:
          - ugc-operations
          - auth-api
    depends_on:
      - auth-service
      - ugc-operations-service
    expose:
      - 80
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_spr10
    restart: always
    environment:
      <<: *rabbitmq-env
    expose:
      - 5672
      - 15672

  redis:
    image: redis:7.2.3-alpine
    expose:
      - 6379

  postgres-authdb:
    image: postgres:15
    environment:
      <<: *auth-env
    expose:
      - 5432
  
  postgres-notificationdb:
    image: postgres:15
    environment:
      <<: *notification-env
    expose:
      - 5432

  auth-service:
    build: auth_service
    image: auth_service_spr10
    environment:
      <<: *auth-env
    expose:
      - 8000
    depends_on:
      - postgres-authdb
      - redis

  auth-service-migrations:
    image: auth_service_spr10
    environment:
      <<: *auth-migrations-env
    expose:
      - 8000
    depends_on:
      - postgres-authdb
      - redis

  notification-service:
    build: notification_service
    image: notification_service_spr10
    environment:
      <<: *notification-env
    expose:
      - 8000
    depends_on:
      - postgres-notificationdb

  notifications-service-migrations:
    image: notification_service_spr10
    environment:
      <<: *notification-env
      RUN_CMD: migrations
    expose:
      - 8000
    depends_on:
      - postgres-notificationdb
  
  notification-service-tests:
    build: notification_service
    image: notification_service_spr10
    environment:
      <<: *notification-env
      RUN_CMD: tests
    expose:
      - 8000
    depends_on:
      - postgres-notificationdb
