version: "3"

services:

  nginx:
    build: nginx
    container_name: nginx_spr10
    restart: always
    ports:
      - "8080:80"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_spr10
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    expose:
      - 5672
      - 15672
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7.2.3-alpine
    container_name: redis_spr10
    restart: always
    expose:
      - 6379

  postgres-authdb:
    image: postgres:15
    container_name: postgres_authdb_spr10
    restart: always
    env_file: auth_service/.env
    expose:
      - 5432

#  postgres-notificationsdb:
#    image: postgres:15
#    container_name: postgres_moviesdb_spr10
#    restart: always
#    env_file: notifications_api/.env
#    expose:
#      - 5432

  auth-service:
    build: auth_service
    image: auth_service_spr10
    container_name: auth_service_spr10
    restart: always
    env_file: auth_service/.env
    expose:
      - 8000
    depends_on:
      - postgres-authdb
      - redis
