name: Linters and Formatters

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Checks:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Lint with Ruff
        uses: chartboost/ruff-action@v1
        with:
          version: 0.2.2
          src: './auth_service'
          args: --line-length 79
      
      - name: "telegram Notification"
        uses: "appleboy/telegram-action@master"
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: ${{ vars.PROJECT_NAME }} ${{ github.job }} for ${{ github.ref_name }} finished with ${{ job.status }}
