name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4


      - name: Run tests
        run: docker-compose -f docker-compose.tests.yaml up --build --exit-code-from notifications-service-tests --abort-on-container-exit

  Notify:
    runs-on: ubuntu-latest
    needs: Tests
    if: ${{ always() }}
    steps:
      - name: Set message
        id: set_message
        run: |
          ref_name=$(basename ${{ github.event.pull_request.head.ref }})
          if [[ "${{ needs.linters.result }}" == 'failure' ]]; then
            echo "MESSAGE=${{ vars.PROJECT_NAME }}: Tests for ${ref_name} finished with error." >> $GITHUB_ENV
          else
            echo "MESSAGE=${{ vars.PROJECT_NAME }}: Tests for ${ref_name} finished successfully." >> $GITHUB_ENV
          fi
        shell: bash

      - name: Debug message
        run: |
          echo "Debug: Message is: $MESSAGE"
      - name: Send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ env.MESSAGE }}