name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4


      - name: Run tests
        run: docker-compose -f docker-compose.tests.yaml up --build --exit-code-from notifications-service-tests --abort-on-container-exit

      - name: "telegram Notification"
        uses: "appleboy/telegram-action@master"
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: ${{ vars.PROJECT_NAME }} ${{ github.job }} for ${{ github.ref_name }} finished with ${{ job.status }}
